export const SET_USERNAME = 'SET_USERNAME'
export const SET_PASSWORD = 'SET_PASSWORD'
export const SET_CONFIRMPASSWORD = 'SET_CONFIRMPASSWORD'
export const SET_EMAIL = 'SET_EMAIL'

export const SET_USERNAME_VALIDATE = 'SET_USERNAME_VALIDATE'
export const SET_PASSWORD_VALIDATE = 'SET_PASSWORD_VALIDATE'
export const SET_CONFIRMPASSWORD_VALIDATE = 'SET_CONFIRMPASSWORD_VALIDATE'
export const SET_EMAIL_VALIDATE = 'SET_EMAIL_VALIDATE'