export const SET_USERNAME = 'SET_USERNAME'
export const SET_PASSWORD = 'SET_PASSWORD'
export const SET_USERNAME_VALIDATE = 'SET_USERNAME_VALIDATE'
export const SET_PASSWORD_VALIDATE = 'SET_PASSWORD_VALIDATE'